### ISSUE TITLE
Browser default scrollbars not being hidden in Chrome/Firefox when using page zoom

### ISSUE THREAD

**Issue by tomfin46** [malte-wessel/react-custom-scrollbars#50] opened 2016-05-23 10:49 UTC
Have only been able to reproduce this in Chrome and Firefox, seems ok in both IE11 and Edge.
Using the latest 4.0.0-beta.1 release although can see the issue on the projects demo page as shown below

Chrome:
![image](https://cloud.githubusercontent.com/assets/3466190/15468425/1d30556e-20dc-11e6-8882-8d10d0d57209.png)

IE11
![image](https://cloud.githubusercontent.com/assets/3466190/15468448/38d67ec4-20dc-11e6-8b42-e0eb1d4a61d4.png)

**Comment by malte-wessel** [comment] 2016-05-26 09:15
This seems to be a problem on Windows. Can't reproduce on OSX.
I guess there's an issue with [`getScrollbarsWidth`](https://github.com/malte-wessel/react-custom-scrollbars/blob/master/src/utils/getScrollbarWidth.js). Would be cool if you could investigate on this!

**Comment by simonkberg** [comment] 2016-06-02 13:53
I'm able to repro on linux, however it only happens when you zoom out *after* the initial load. Since the scrollbars don't "scale", they eventually become visible as the element sizes shrink. `getScrollbarsWidth` would need to be triggered also "on zoom" to get the correct size values, but no browser event is available for this so it would require some ugly workarounds to fix. 

One idea would be to add extra padding on the "view" to offset the native scrollbars even more:
```js
const scrollbarWidth = getScrollbarsWidth()
const extraOffset = scrollbarWidth * 10
const styleHack = {
  right: `-${extraOffset}px`,
  bottom: `-${extraOffset}px`,
  paddingRight: `${extraOffset - scrollbarWidth}px`
  paddingBottom: `${extraOffset - scrollbarWidth}px`
}
```
Or something similar. Still pretty ugly, but it works in my quick browser tests on the demo page.

**Comment by realcr** [comment] 2016-06-05 08:52
I can reproduce this bug on Linux Ubuntu with both Firefox and Chrome.

**Comment by realcr** [comment] 2016-06-05 09:05
I tried to change
    
    overflow: 'scroll',

into 

    overflow: 'hidden',

at https://github.com/malte-wessel/react-custom-scrollbars/blob/master/src/Scrollbars/styles.js#L19
This helps a little bit, as you don't see the scrollbars any more when scrolling. It is still not perfect, as there is a difference in color around the edges.

Does it break anything to change it from 'scroll' to 'hidden'?

**Comment by malte-wessel** [comment] 2016-06-05 09:12
Yes, I guess that the native scrolling behaviour will be disabled. I'll see what I can do about this next week.

**Comment by realcr** [comment] 2016-06-05 09:16
@male-wessel: I see. Thank you for your great work!

**Comment by danbrianwhite** [comment] 2016-06-16 18:08
I don't have time at the moment to update my branch for a pull request (https://github.com/danbrianwhite/react-custom-scrollbars/). In my branch I changed package name and checked in lib folder (react-custom-scrollbars-plus). This issue is resolved in my branch as long as you reload the browser after zooming in. If you wanted to update the scrollbars when someone zoomed in with the page loaded, you would have to update the scrollbar width upon the change (or poll the window for size changes).

The changes I made also always displaying scrollbars for OSx and iOS. I still used the native scroll window so the scrolling is still native performance on iOS.

**Comment by Towave** [comment] 2016-10-04 18:17
I've resolved that problem ^

**Comment by StephanUa** [comment] 2016-10-28 06:58
Do you have any ideas how to fix this issue?

**Closed** 2017-10-28 09:16 UTC
Labels: bug

**Comment by philraj** [comment] 2018-01-18 21:56
This doesn't seem to be fixed in recent version of Chrome and Firefox, on macOS at least.

**Comment by philraj** [comment] 2018-02-14 22:36
This should be re-opened, it's no longer fixed in Windows either.

**Comment by RussCoder** [comment] 2019-08-07 09:13
@malte-wessel I also have the same problem. When I zoom out the page, native scrollbars appear. The issue should be re-opened,
